services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql

  backup:
    container_name: backup
    image: mysql
    depends_on:
      - mysql
    volumes:
      - ./backups:/backup
    entrypoint: /bin/bash -c "trap 'mysqldump -h mysql -uroot -prootpassword nestdb > /backup/backup_$(date +\"%Y%m%d_%H%M%S\").sql' EXIT && tail -f /dev/null"
    volumes_from:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 5555:80
    environment:
      - PMA_ARBITRARY=1

  nestjs:
    container_name: api
    build:
      context: .
      target: local
    env_file:
      - ${ENV_FILE}
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      # App port
      - 8888:3000
      # Debug port
      - 9229:9229
    depends_on:
      - mysql
    command: yarn run start:debug

volumes:
  mysql_data:
  backups:
