services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
    volumes:
      - mysql_data:/var/lib/mysql

  backup:
    container_name: backup
    image: mysql
    depends_on:
      - mysql
    volumes:
      - ./backups:/backup
    entrypoint: /bin/bash -c "trap 'mysqldump -h mysql -uroot -prootpassword nestdb > /backup/backup_$(date +\"%Y%m%d_%H%M%S\").sql' EXIT && tail -f /dev/null"
    volumes_from:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 5555:80
    environment:
      - PMA_ARBITRARY=1

  nestjs:
    container_name: api
    build:
      context: .
      target: local
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestdb
      - DB_USER=root
      - NODE_ENV:development
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      # App port
      - 8888:3000
      # Debug port
      - 9229:9229
    depends_on:
      - mysql
    command: yarn run start:debug

volumes:
  mysql_data:
  backups:
