services:
  # mysql:
  #   image: mysql
  #   container_name: mysql_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: nestdb
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./db/:/var/lib/mysql

  nestjs:
    container_name: nestjs_api
    build: .
    environment:
      - PORT=3000
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestdb
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '8888:3000'
    # command: 'yarn && yarn run start:dev'
    # depends_on:
    #   - mysql
