services:
  #   mysql:
  #     image: mysql
  #     restart: always
  #     container_name: mysql
  #     environment:
  #       MYSQL_ROOT_PASSWORD: rootpassword
  #       MYSQL_DATABASE: nestdb
  #     # ports:
  #     #   - '3306:3306'
  #     volumes:
  #       - ./db/:/var/lib/mysql

  #   adminer:
  #     image: adminer
  #     container_name: adminer
  #     restart: always
  #     ports:
  #       - 7777:8080

  #   phpmyadmin:
  #     image: phpmyadmin
  #     container_name: phpmyadmin
  #     restart: always
  #     ports:
  #       - 5555:80
  #     environment:
  #       - PMA_ARBITRARY=1

  nestjs:
    container_name: api
    build:
      context: .
      target: local
    environment:
      - PORT=3000
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestdb
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - '8888:3000'
    # depends_on:
    #   - mysql
