services:
  mysql:
    #   build:
    #     context: .
    #     dockerfile: Mysql.Dockerfile
    image: mysql
    # restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
      # DB_HOST: mysql
      # DB_USER: root
    # ports:
    #   - '3306:3306'
    # stop_grace_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./backups:/var/backups/mysql
    # command:
    #   ['sh', '-c', "trap 'sh /usr/local/bin/backup.sh' EXIT; exec mysqld"]

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - 7777:8080

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    # restart: always
    ports:
      - 5555:80
    environment:
      - PMA_ARBITRARY=1

  nestjs:
    container_name: api
    build:
      context: .
      target: local
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestdb
      - DB_USER=root
      - NODE_ENV:development
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      # App port
      - 8888:3000
      # Debug port
      - 9229:9229
    depends_on:
      - mysql
    command: yarn run start:debug

volumes:
  mysql_data:
