services:
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql

  backup:
    container_name: backup
    image: mysql
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./backups:/backup
      - ./backup.entry.sh:/backup.entry.sh
    volumes_from:
      - mysql
    depends_on:
      - mysql
    entrypoint: /backup.entry.sh

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 5555:80
    environment:
      - PMA_ARBITRARY=1

  nestjs:
    container_name: api
    build:
      context: .
      target: local
    env_file:
      - ${ENV_FILE}
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      # App port
      - 8888:3000
      # Debug port
      - 9229:9229
    depends_on:
      - mysql
    command: yarn run start:debug

volumes:
  mysql_data:
  backups:
